// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rum.proto

package rumrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ISequence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Input         []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISequence) Reset() {
	*x = ISequence{}
	mi := &file_rum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISequence) ProtoMessage() {}

func (x *ISequence) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISequence.ProtoReflect.Descriptor instead.
func (*ISequence) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{0}
}

func (x *ISequence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ISequence) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ISequence) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ISequence) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type IPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ISequence             `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Push          bool                   `protobuf:"varint,3,opt,name=push,proto3" json:"push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPost) Reset() {
	*x = IPost{}
	mi := &file_rum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPost) ProtoMessage() {}

func (x *IPost) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPost.ProtoReflect.Descriptor instead.
func (*IPost) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{1}
}

func (x *IPost) GetProfile() *ISequence {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *IPost) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

type IDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ISequence             `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Remove        bool                   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDelete) Reset() {
	*x = IDelete{}
	mi := &file_rum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDelete) ProtoMessage() {}

func (x *IDelete) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDelete.ProtoReflect.Descriptor instead.
func (*IDelete) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{2}
}

func (x *IDelete) GetProfile() *ISequence {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *IDelete) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

type IDeactivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ISequence             `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Deactive      bool                   `protobuf:"varint,3,opt,name=deactive,proto3" json:"deactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeactivate) Reset() {
	*x = IDeactivate{}
	mi := &file_rum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeactivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeactivate) ProtoMessage() {}

func (x *IDeactivate) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeactivate.ProtoReflect.Descriptor instead.
func (*IDeactivate) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{3}
}

func (x *IDeactivate) GetProfile() *ISequence {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *IDeactivate) GetDeactive() bool {
	if x != nil {
		return x.Deactive
	}
	return false
}

type IActivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ISequence             `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Activate      bool                   `protobuf:"varint,3,opt,name=activate,proto3" json:"activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IActivate) Reset() {
	*x = IActivate{}
	mi := &file_rum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IActivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IActivate) ProtoMessage() {}

func (x *IActivate) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IActivate.ProtoReflect.Descriptor instead.
func (*IActivate) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{4}
}

func (x *IActivate) GetProfile() *ISequence {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *IActivate) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

type IPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []*IPost               `protobuf:"bytes,1,rep,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPostRequest) Reset() {
	*x = IPostRequest{}
	mi := &file_rum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPostRequest) ProtoMessage() {}

func (x *IPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPostRequest.ProtoReflect.Descriptor instead.
func (*IPostRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{5}
}

func (x *IPostRequest) GetPost() []*IPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type IDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delete        []*IDelete             `protobuf:"bytes,1,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeleteRequest) Reset() {
	*x = IDeleteRequest{}
	mi := &file_rum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeleteRequest) ProtoMessage() {}

func (x *IDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeleteRequest.ProtoReflect.Descriptor instead.
func (*IDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{6}
}

func (x *IDeleteRequest) GetDelete() []*IDelete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type IDeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deactivate    []*IDeactivate         `protobuf:"bytes,1,rep,name=deactivate,proto3" json:"deactivate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeactivateRequest) Reset() {
	*x = IDeactivateRequest{}
	mi := &file_rum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeactivateRequest) ProtoMessage() {}

func (x *IDeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeactivateRequest.ProtoReflect.Descriptor instead.
func (*IDeactivateRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{7}
}

func (x *IDeactivateRequest) GetDeactivate() []*IDeactivate {
	if x != nil {
		return x.Deactivate
	}
	return nil
}

type IActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activate      []*IActivate           `protobuf:"bytes,1,rep,name=activate,proto3" json:"activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IActivateRequest) Reset() {
	*x = IActivateRequest{}
	mi := &file_rum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IActivateRequest) ProtoMessage() {}

func (x *IActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IActivateRequest.ProtoReflect.Descriptor instead.
func (*IActivateRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{8}
}

func (x *IActivateRequest) GetActivate() []*IActivate {
	if x != nil {
		return x.Activate
	}
	return nil
}

type IRemoveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delete        []*IDelete             `protobuf:"bytes,1,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IRemoveServiceRequest) Reset() {
	*x = IRemoveServiceRequest{}
	mi := &file_rum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IRemoveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRemoveServiceRequest) ProtoMessage() {}

func (x *IRemoveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRemoveServiceRequest.ProtoReflect.Descriptor instead.
func (*IRemoveServiceRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{9}
}

func (x *IRemoveServiceRequest) GetDelete() []*IDelete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type IDeactivateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delete        []*IDelete             `protobuf:"bytes,1,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeactivateServiceRequest) Reset() {
	*x = IDeactivateServiceRequest{}
	mi := &file_rum_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeactivateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeactivateServiceRequest) ProtoMessage() {}

func (x *IDeactivateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeactivateServiceRequest.ProtoReflect.Descriptor instead.
func (*IDeactivateServiceRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{10}
}

func (x *IDeactivateServiceRequest) GetDelete() []*IDelete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type IActivateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delete        []*IDelete             `protobuf:"bytes,1,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IActivateServiceRequest) Reset() {
	*x = IActivateServiceRequest{}
	mi := &file_rum_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IActivateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IActivateServiceRequest) ProtoMessage() {}

func (x *IActivateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IActivateServiceRequest.ProtoReflect.Descriptor instead.
func (*IActivateServiceRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{11}
}

func (x *IActivateServiceRequest) GetDelete() []*IDelete {
	if x != nil {
		return x.Delete
	}
	return nil
}

type IPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPostResponse) Reset() {
	*x = IPostResponse{}
	mi := &file_rum_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPostResponse) ProtoMessage() {}

func (x *IPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPostResponse.ProtoReflect.Descriptor instead.
func (*IPostResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{12}
}

func (x *IPostResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeleteResponse) Reset() {
	*x = IDeleteResponse{}
	mi := &file_rum_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeleteResponse) ProtoMessage() {}

func (x *IDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeleteResponse.ProtoReflect.Descriptor instead.
func (*IDeleteResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{13}
}

func (x *IDeleteResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IActivateResponse) Reset() {
	*x = IActivateResponse{}
	mi := &file_rum_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IActivateResponse) ProtoMessage() {}

func (x *IActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IActivateResponse.ProtoReflect.Descriptor instead.
func (*IActivateResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{14}
}

func (x *IActivateResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IDeactivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeactivateResponse) Reset() {
	*x = IDeactivateResponse{}
	mi := &file_rum_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeactivateResponse) ProtoMessage() {}

func (x *IDeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeactivateResponse.ProtoReflect.Descriptor instead.
func (*IDeactivateResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{15}
}

func (x *IDeactivateResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IRemoveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IRemoveServiceResponse) Reset() {
	*x = IRemoveServiceResponse{}
	mi := &file_rum_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IRemoveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRemoveServiceResponse) ProtoMessage() {}

func (x *IRemoveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRemoveServiceResponse.ProtoReflect.Descriptor instead.
func (*IRemoveServiceResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{16}
}

func (x *IRemoveServiceResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IDeactivateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDeactivateServiceResponse) Reset() {
	*x = IDeactivateServiceResponse{}
	mi := &file_rum_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDeactivateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDeactivateServiceResponse) ProtoMessage() {}

func (x *IDeactivateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDeactivateServiceResponse.ProtoReflect.Descriptor instead.
func (*IDeactivateServiceResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{17}
}

func (x *IDeactivateServiceResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IActivateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IActivateServiceResponse) Reset() {
	*x = IActivateServiceResponse{}
	mi := &file_rum_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IActivateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IActivateServiceResponse) ProtoMessage() {}

func (x *IActivateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IActivateServiceResponse.ProtoReflect.Descriptor instead.
func (*IActivateServiceResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{18}
}

func (x *IActivateServiceResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

var File_rum_proto protoreflect.FileDescriptor

const file_rum_proto_rawDesc = "" +
	"\n" +
	"\trum.proto\x12\x06rumrpc\"c\n" +
	"\tISequence\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\"H\n" +
	"\x05IPost\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.rumrpc.ISequenceR\aprofile\x12\x12\n" +
	"\x04push\x18\x03 \x01(\bR\x04push\"N\n" +
	"\aIDelete\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.rumrpc.ISequenceR\aprofile\x12\x16\n" +
	"\x06remove\x18\x03 \x01(\bR\x06remove\"V\n" +
	"\vIDeactivate\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.rumrpc.ISequenceR\aprofile\x12\x1a\n" +
	"\bdeactive\x18\x03 \x01(\bR\bdeactive\"T\n" +
	"\tIActivate\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.rumrpc.ISequenceR\aprofile\x12\x1a\n" +
	"\bactivate\x18\x03 \x01(\bR\bactivate\"1\n" +
	"\fIPostRequest\x12!\n" +
	"\x04post\x18\x01 \x03(\v2\r.rumrpc.IPostR\x04post\"9\n" +
	"\x0eIDeleteRequest\x12'\n" +
	"\x06delete\x18\x01 \x03(\v2\x0f.rumrpc.IDeleteR\x06delete\"I\n" +
	"\x12IDeactivateRequest\x123\n" +
	"\n" +
	"deactivate\x18\x01 \x03(\v2\x13.rumrpc.IDeactivateR\n" +
	"deactivate\"A\n" +
	"\x10IActivateRequest\x12-\n" +
	"\bactivate\x18\x01 \x03(\v2\x11.rumrpc.IActivateR\bactivate\"@\n" +
	"\x15IRemoveServiceRequest\x12'\n" +
	"\x06delete\x18\x01 \x03(\v2\x0f.rumrpc.IDeleteR\x06delete\"D\n" +
	"\x19IDeactivateServiceRequest\x12'\n" +
	"\x06delete\x18\x01 \x03(\v2\x0f.rumrpc.IDeleteR\x06delete\"B\n" +
	"\x17IActivateServiceRequest\x12'\n" +
	"\x06delete\x18\x01 \x03(\v2\x0f.rumrpc.IDeleteR\x06delete\")\n" +
	"\rIPostResponse\x12\x18\n" +
	"\asucceed\x18\x01 \x01(\bR\asucceed\"+\n" +
	"\x0fIDeleteResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"-\n" +
	"\x11IActivateResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"/\n" +
	"\x13IDeactivateResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"2\n" +
	"\x16IRemoveServiceResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"6\n" +
	"\x1aIDeactivateServiceResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"4\n" +
	"\x18IActivateServiceResponse\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed2\x88\x04\n" +
	"\fOnRumService\x123\n" +
	"\x04POST\x12\x14.rumrpc.IPostRequest\x1a\x15.rumrpc.IPostResponse\x129\n" +
	"\x06DELETE\x12\x16.rumrpc.IDeleteRequest\x1a\x17.rumrpc.IDeleteResponse\x12?\n" +
	"\bACTIVATE\x12\x18.rumrpc.IActivateRequest\x1a\x19.rumrpc.IActivateResponse\x12E\n" +
	"\n" +
	"DEACTIVATE\x12\x1a.rumrpc.IDeactivateRequest\x1a\x1b.rumrpc.IDeactivateResponse\x12N\n" +
	"\rREMOVESERVICE\x12\x1d.rumrpc.IRemoveServiceRequest\x1a\x1e.rumrpc.IRemoveServiceResponse\x12Z\n" +
	"\x11DEACTIVATESERVICE\x12!.rumrpc.IDeactivateServiceRequest\x1a\".rumrpc.IDeactivateServiceResponse\x12T\n" +
	"\x0fACTIVATESERVICE\x12\x1f.rumrpc.IActivateServiceRequest\x1a .rumrpc.IActivateServiceResponseB\x11Z\x0fapp/main/rumrpcb\x06proto3"

var (
	file_rum_proto_rawDescOnce sync.Once
	file_rum_proto_rawDescData []byte
)

func file_rum_proto_rawDescGZIP() []byte {
	file_rum_proto_rawDescOnce.Do(func() {
		file_rum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rum_proto_rawDesc), len(file_rum_proto_rawDesc)))
	})
	return file_rum_proto_rawDescData
}

var file_rum_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_rum_proto_goTypes = []any{
	(*ISequence)(nil),                  // 0: rumrpc.ISequence
	(*IPost)(nil),                      // 1: rumrpc.IPost
	(*IDelete)(nil),                    // 2: rumrpc.IDelete
	(*IDeactivate)(nil),                // 3: rumrpc.IDeactivate
	(*IActivate)(nil),                  // 4: rumrpc.IActivate
	(*IPostRequest)(nil),               // 5: rumrpc.IPostRequest
	(*IDeleteRequest)(nil),             // 6: rumrpc.IDeleteRequest
	(*IDeactivateRequest)(nil),         // 7: rumrpc.IDeactivateRequest
	(*IActivateRequest)(nil),           // 8: rumrpc.IActivateRequest
	(*IRemoveServiceRequest)(nil),      // 9: rumrpc.IRemoveServiceRequest
	(*IDeactivateServiceRequest)(nil),  // 10: rumrpc.IDeactivateServiceRequest
	(*IActivateServiceRequest)(nil),    // 11: rumrpc.IActivateServiceRequest
	(*IPostResponse)(nil),              // 12: rumrpc.IPostResponse
	(*IDeleteResponse)(nil),            // 13: rumrpc.IDeleteResponse
	(*IActivateResponse)(nil),          // 14: rumrpc.IActivateResponse
	(*IDeactivateResponse)(nil),        // 15: rumrpc.IDeactivateResponse
	(*IRemoveServiceResponse)(nil),     // 16: rumrpc.IRemoveServiceResponse
	(*IDeactivateServiceResponse)(nil), // 17: rumrpc.IDeactivateServiceResponse
	(*IActivateServiceResponse)(nil),   // 18: rumrpc.IActivateServiceResponse
}
var file_rum_proto_depIdxs = []int32{
	0,  // 0: rumrpc.IPost.profile:type_name -> rumrpc.ISequence
	0,  // 1: rumrpc.IDelete.profile:type_name -> rumrpc.ISequence
	0,  // 2: rumrpc.IDeactivate.profile:type_name -> rumrpc.ISequence
	0,  // 3: rumrpc.IActivate.profile:type_name -> rumrpc.ISequence
	1,  // 4: rumrpc.IPostRequest.post:type_name -> rumrpc.IPost
	2,  // 5: rumrpc.IDeleteRequest.delete:type_name -> rumrpc.IDelete
	3,  // 6: rumrpc.IDeactivateRequest.deactivate:type_name -> rumrpc.IDeactivate
	4,  // 7: rumrpc.IActivateRequest.activate:type_name -> rumrpc.IActivate
	2,  // 8: rumrpc.IRemoveServiceRequest.delete:type_name -> rumrpc.IDelete
	2,  // 9: rumrpc.IDeactivateServiceRequest.delete:type_name -> rumrpc.IDelete
	2,  // 10: rumrpc.IActivateServiceRequest.delete:type_name -> rumrpc.IDelete
	5,  // 11: rumrpc.OnRumService.POST:input_type -> rumrpc.IPostRequest
	6,  // 12: rumrpc.OnRumService.DELETE:input_type -> rumrpc.IDeleteRequest
	8,  // 13: rumrpc.OnRumService.ACTIVATE:input_type -> rumrpc.IActivateRequest
	7,  // 14: rumrpc.OnRumService.DEACTIVATE:input_type -> rumrpc.IDeactivateRequest
	9,  // 15: rumrpc.OnRumService.REMOVESERVICE:input_type -> rumrpc.IRemoveServiceRequest
	10, // 16: rumrpc.OnRumService.DEACTIVATESERVICE:input_type -> rumrpc.IDeactivateServiceRequest
	11, // 17: rumrpc.OnRumService.ACTIVATESERVICE:input_type -> rumrpc.IActivateServiceRequest
	12, // 18: rumrpc.OnRumService.POST:output_type -> rumrpc.IPostResponse
	13, // 19: rumrpc.OnRumService.DELETE:output_type -> rumrpc.IDeleteResponse
	14, // 20: rumrpc.OnRumService.ACTIVATE:output_type -> rumrpc.IActivateResponse
	15, // 21: rumrpc.OnRumService.DEACTIVATE:output_type -> rumrpc.IDeactivateResponse
	16, // 22: rumrpc.OnRumService.REMOVESERVICE:output_type -> rumrpc.IRemoveServiceResponse
	17, // 23: rumrpc.OnRumService.DEACTIVATESERVICE:output_type -> rumrpc.IDeactivateServiceResponse
	18, // 24: rumrpc.OnRumService.ACTIVATESERVICE:output_type -> rumrpc.IActivateServiceResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rum_proto_init() }
func file_rum_proto_init() {
	if File_rum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rum_proto_rawDesc), len(file_rum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rum_proto_goTypes,
		DependencyIndexes: file_rum_proto_depIdxs,
		MessageInfos:      file_rum_proto_msgTypes,
	}.Build()
	File_rum_proto = out.File
	file_rum_proto_goTypes = nil
	file_rum_proto_depIdxs = nil
}
