// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: rum.proto

package rumrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnRumService_POST_FullMethodName              = "/rumrpc.OnRumService/POST"
	OnRumService_DELETE_FullMethodName            = "/rumrpc.OnRumService/DELETE"
	OnRumService_ACTIVATE_FullMethodName          = "/rumrpc.OnRumService/ACTIVATE"
	OnRumService_DEACTIVATE_FullMethodName        = "/rumrpc.OnRumService/DEACTIVATE"
	OnRumService_REMOVESERVICE_FullMethodName     = "/rumrpc.OnRumService/REMOVESERVICE"
	OnRumService_DEACTIVATESERVICE_FullMethodName = "/rumrpc.OnRumService/DEACTIVATESERVICE"
	OnRumService_ACTIVATESERVICE_FullMethodName   = "/rumrpc.OnRumService/ACTIVATESERVICE"
)

// OnRumServiceClient is the client API for OnRumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnRumServiceClient interface {
	POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error)
	DELETE(ctx context.Context, in *IDeleteRequest, opts ...grpc.CallOption) (*IDeleteResponse, error)
	ACTIVATE(ctx context.Context, in *IActivateRequest, opts ...grpc.CallOption) (*IActivateResponse, error)
	DEACTIVATE(ctx context.Context, in *IDeactivateRequest, opts ...grpc.CallOption) (*IDeactivateResponse, error)
	REMOVESERVICE(ctx context.Context, in *IRemoveServiceRequest, opts ...grpc.CallOption) (*IRemoveServiceResponse, error)
	DEACTIVATESERVICE(ctx context.Context, in *IDeactivateServiceRequest, opts ...grpc.CallOption) (*IDeactivateServiceResponse, error)
	ACTIVATESERVICE(ctx context.Context, in *IActivateServiceRequest, opts ...grpc.CallOption) (*IActivateServiceResponse, error)
}

type onRumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnRumServiceClient(cc grpc.ClientConnInterface) OnRumServiceClient {
	return &onRumServiceClient{cc}
}

func (c *onRumServiceClient) POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPostResponse)
	err := c.cc.Invoke(ctx, OnRumService_POST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DELETE(ctx context.Context, in *IDeleteRequest, opts ...grpc.CallOption) (*IDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeleteResponse)
	err := c.cc.Invoke(ctx, OnRumService_DELETE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ACTIVATE(ctx context.Context, in *IActivateRequest, opts ...grpc.CallOption) (*IActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateResponse)
	err := c.cc.Invoke(ctx, OnRumService_ACTIVATE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DEACTIVATE(ctx context.Context, in *IDeactivateRequest, opts ...grpc.CallOption) (*IDeactivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateResponse)
	err := c.cc.Invoke(ctx, OnRumService_DEACTIVATE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) REMOVESERVICE(ctx context.Context, in *IRemoveServiceRequest, opts ...grpc.CallOption) (*IRemoveServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IRemoveServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_REMOVESERVICE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DEACTIVATESERVICE(ctx context.Context, in *IDeactivateServiceRequest, opts ...grpc.CallOption) (*IDeactivateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_DEACTIVATESERVICE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ACTIVATESERVICE(ctx context.Context, in *IActivateServiceRequest, opts ...grpc.CallOption) (*IActivateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_ACTIVATESERVICE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnRumServiceServer is the server API for OnRumService service.
// All implementations must embed UnimplementedOnRumServiceServer
// for forward compatibility.
type OnRumServiceServer interface {
	POST(context.Context, *IPostRequest) (*IPostResponse, error)
	DELETE(context.Context, *IDeleteRequest) (*IDeleteResponse, error)
	ACTIVATE(context.Context, *IActivateRequest) (*IActivateResponse, error)
	DEACTIVATE(context.Context, *IDeactivateRequest) (*IDeactivateResponse, error)
	REMOVESERVICE(context.Context, *IRemoveServiceRequest) (*IRemoveServiceResponse, error)
	DEACTIVATESERVICE(context.Context, *IDeactivateServiceRequest) (*IDeactivateServiceResponse, error)
	ACTIVATESERVICE(context.Context, *IActivateServiceRequest) (*IActivateServiceResponse, error)
	mustEmbedUnimplementedOnRumServiceServer()
}

// UnimplementedOnRumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnRumServiceServer struct{}

func (UnimplementedOnRumServiceServer) POST(context.Context, *IPostRequest) (*IPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POST not implemented")
}
func (UnimplementedOnRumServiceServer) DELETE(context.Context, *IDeleteRequest) (*IDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DELETE not implemented")
}
func (UnimplementedOnRumServiceServer) ACTIVATE(context.Context, *IActivateRequest) (*IActivateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACTIVATE not implemented")
}
func (UnimplementedOnRumServiceServer) DEACTIVATE(context.Context, *IDeactivateRequest) (*IDeactivateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DEACTIVATE not implemented")
}
func (UnimplementedOnRumServiceServer) REMOVESERVICE(context.Context, *IRemoveServiceRequest) (*IRemoveServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method REMOVESERVICE not implemented")
}
func (UnimplementedOnRumServiceServer) DEACTIVATESERVICE(context.Context, *IDeactivateServiceRequest) (*IDeactivateServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DEACTIVATESERVICE not implemented")
}
func (UnimplementedOnRumServiceServer) ACTIVATESERVICE(context.Context, *IActivateServiceRequest) (*IActivateServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACTIVATESERVICE not implemented")
}
func (UnimplementedOnRumServiceServer) mustEmbedUnimplementedOnRumServiceServer() {}
func (UnimplementedOnRumServiceServer) testEmbeddedByValue()                      {}

// UnsafeOnRumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnRumServiceServer will
// result in compilation errors.
type UnsafeOnRumServiceServer interface {
	mustEmbedUnimplementedOnRumServiceServer()
}

func RegisterOnRumServiceServer(s grpc.ServiceRegistrar, srv OnRumServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnRumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnRumService_ServiceDesc, srv)
}

func _OnRumService_POST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).POST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_POST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).POST(ctx, req.(*IPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DELETE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DELETE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DELETE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DELETE(ctx, req.(*IDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ACTIVATE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ACTIVATE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ACTIVATE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ACTIVATE(ctx, req.(*IActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DEACTIVATE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DEACTIVATE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DEACTIVATE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DEACTIVATE(ctx, req.(*IDeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_REMOVESERVICE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IRemoveServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).REMOVESERVICE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_REMOVESERVICE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).REMOVESERVICE(ctx, req.(*IRemoveServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DEACTIVATESERVICE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DEACTIVATESERVICE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DEACTIVATESERVICE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DEACTIVATESERVICE(ctx, req.(*IDeactivateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ACTIVATESERVICE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ACTIVATESERVICE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ACTIVATESERVICE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ACTIVATESERVICE(ctx, req.(*IActivateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnRumService_ServiceDesc is the grpc.ServiceDesc for OnRumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnRumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rumrpc.OnRumService",
	HandlerType: (*OnRumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "POST",
			Handler:    _OnRumService_POST_Handler,
		},
		{
			MethodName: "DELETE",
			Handler:    _OnRumService_DELETE_Handler,
		},
		{
			MethodName: "ACTIVATE",
			Handler:    _OnRumService_ACTIVATE_Handler,
		},
		{
			MethodName: "DEACTIVATE",
			Handler:    _OnRumService_DEACTIVATE_Handler,
		},
		{
			MethodName: "REMOVESERVICE",
			Handler:    _OnRumService_REMOVESERVICE_Handler,
		},
		{
			MethodName: "DEACTIVATESERVICE",
			Handler:    _OnRumService_DEACTIVATESERVICE_Handler,
		},
		{
			MethodName: "ACTIVATESERVICE",
			Handler:    _OnRumService_ACTIVATESERVICE_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rum.proto",
}
