package searchmanager

import (
	"context"
	"fmt"

	"github.com/milvus-io/milvus/client/v2/entity"
	"github.com/milvus-io/milvus/client/v2/milvusclient"
)

// newClient creates a raw milvus connection — shared by both constructors.
func newClient(ctx context.Context, addr, user, pass string) (*milvusclient.Client, error) {
	if addr == "" {
		return nil, fmt.Errorf("milvus address is empty")
	}
	cx, err := milvusclient.New(ctx, &milvusclient.ClientConfig{
		Address:  addr,
		Username: user,
		Password: pass,
	})
	if err != nil {
		return nil, fmt.Errorf("connect milvus at %q: %w", addr, err)
	}
	if cx == nil {
		return nil, fmt.Errorf("milvusclient.New returned nil without error")
	}
	return cx, nil
}

// baseSchema builds the 6 fields shared by both search modes.
// defaultCol: schema name — overwritten per bucket at collection creation time.
// dim: embedding dimension — pass 0 to use DefaultDim.
func baseSchema(defaultCol string, dim int) *entity.Schema {
	if dim == 0 {
		dim = DefaultDim
	}
	return &entity.Schema{
		CollectionName: defaultCol,
		Description:    "rum search engine",
		AutoID:         false,
		Fields: []*entity.Field{
			{
				Name:        FieldID,
				PrimaryKey:  true,
				AutoID:      false,
				Description: "object id — format: <source>:<type>:<unique>",
				DataType:    entity.FieldTypeVarChar,
				TypeParams:  map[string]string{"max_length": fmt.Sprintf("%d", MaxIDLen)},
			},
			{
				Name:        FieldText,
				DataType:    entity.FieldTypeVarChar,
				Description: "raw text chunk that was embedded",
				TypeParams:  map[string]string{"max_length": fmt.Sprintf("%d", MaxTextLen)},
			},
			{
				Name:        FieldEmbedding,
				DataType:    entity.FieldTypeFloatVector,
				Description: "dense float32 embedding — dim must match encoder output",
				TypeParams:  map[string]string{"dim": fmt.Sprintf("%d", dim)},
			},
			{
				Name:        FieldResponse,
				DataType:    entity.FieldTypeVarChar,
				Description: "response from the agent",
				TypeParams:  map[string]string{"max_length": fmt.Sprintf("%d", MaxTextLen)},
			},
			{
				Name:        FieldBranch,
				DataType:    entity.FieldTypeVarChar,
				Description: "branch — format: <project>/<environment>",
				TypeParams:  map[string]string{"max_length": fmt.Sprintf("%d", MaxBranchLen)},
			},
			{
				Name:        FieldDocType,
				DataType:    entity.FieldTypeVarChar,
				Description: "mime-like type — e.g. text/plain, image/png",
				TypeParams:  map[string]string{"max_length": "256"},
			},
			{
				Name:        FieldCreatedAt,
				DataType:    entity.FieldTypeInt64,
				Description: "unix timestamp of insertion",
			},
		},
	}
}

// NewSearch returns a manager wired for dense ANN search only.
// Use Push() to insert, Search() to query.
// dim: embedding dimension — pass 0 to use DefaultDim (768).
func NewSearch(ctx context.Context, addr, user, pass, defaultCol string, dim int) (*SearchManager, error) {
	cx, err := newClient(ctx, addr, user, pass)
	if err != nil {
		return nil, err
	}
	if dim == 0 {
		dim = DefaultDim
	}
	return &SearchManager{
		client: cx,
		ctx:    ctx,
		topK:   DefaultTopK,
		dim:    dim,
		schema: baseSchema(defaultCol, dim),
	}, nil
}

// NewHybridSearch returns a manager wired for dense ANN + BM25 hybrid search.
// Use HPush() to insert, SearchHybrid() to query.
// Do NOT mix with Push()/Search() — the schema has an extra sparse field.
// dim: embedding dimension — pass 0 to use DefaultDim (768).
func NewHybridSearch(ctx context.Context, addr, user, pass, defaultCol string, dim int) (*SearchManager, error) {
	cx, err := newClient(ctx, addr, user, pass)
	if err != nil {
		return nil, err
	}
	if dim == 0 {
		dim = DefaultDim
	}

	sch := baseSchema(defaultCol, dim)

	// enable analyzer on the text input field for BM25
	if len(sch.Fields) > 1 {
		sch.Fields[1] = sch.Fields[1].WithEnableAnalyzer(true)
	}

	// sparse field — dimensionless, auto-populated by BM25 function at insert time
	// HPush() must never insert this column manually
	sch.Fields = append(sch.Fields, &entity.Field{
		Name:        FieldSparseEmbedding,
		DataType:    entity.FieldTypeSparseVector,
		Description: "auto-generated by BM25 function from text field",
	})

	// BM25 function: text → sparseEmbedding
	sch.WithFunction(entity.NewFunction().
		WithName("bm25").
		WithInputFields(FieldText).
		WithOutputFields(FieldSparseEmbedding).
		WithType(entity.FunctionTypeBM25))

	return &SearchManager{
		client: cx,
		ctx:    ctx,
		topK:   DefaultTopK,
		dim:    dim,
		schema: sch,
	}, nil
}

// BestMatch returns the top match
// note: current we search for less value than higher cause less value means the closer result to current search
func BestMatch(scores []ISearch) *ISearch {
	if len(scores) == 0 {
		return nil
	}
	cur := scores[0]
	for _, r := range scores[1:] {
		if r.RawScore < cur.RawScore {
			cur = r
		}
	}
	return &cur
}
